name: freshrss
services:
  freshrss:
    container_name: freshrss
    env_file:
      - common.env
    hostname: "${DOCKER_HOSTNAME}-freshrss"
    image: lscr.io/linuxserver/freshrss:latest
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    networks:
      - db-freshrss
      - proxy-freshrss
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONTAINER_BASE_DIR}/freshrss:/config

networks:
  db-freshrss:
    external: true

  proxy-freshrss:
    external: true

