name: jellyfin
services:
  jellyfin:
    container_name: jellyfin
    env_file:
      - common.env
    hostname: "${DOCKER_HOSTNAME}-jellyfin"
    image: lscr.io/linuxserver/jellyfin:latest
    networks:
      - proxy-jellyfin
    restart: unless-stopped
    environment:
      - JELLYFIN_DATA_DIR=/data
      - JELLYFIN_CACHE_DIR=/cache
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONTAINER_BASE_DIR}/jellyfin/config:/config
      - ${MEDIAS_DIR}/library:/data
      - ${CONTAINER_BASE_DIR}/jellyfin/cache:/cache

networks:
  proxy-jellyfin:
    external: true

