name: mail-to-rss
services:
  mail-to-rss:
    container_name: mail-to-rss
    env_file:
      - common.env
      - mail-to-rss.secrets
    hostname: "${DOCKER_HOSTNAME}-mail-to-rss"
    image: zayon/mail-to-rss:beta
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    networks:
      - proxy-mail-to-rss
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONTAINER_BASE_DIR}/mail-to-rss:/app/var

networks:
  proxy-mail-to-rss:
    external: true

