name: ntfy
services:
  ntfy:
    container_name: ntfy
    env_file:
      - common.env
    hostname: "${DOCKER_HOSTNAME}-ntfy"
    user: ${UID}:${GID}
    image: binwiederhier/ntfy:latest
    networks:
      - proxy-ntfy
    restart: unless-stopped
    command:
      - serve
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONTAINER_BASE_DIR}/ntfy:/etc/ntfy
      - ntfy_cache:/var/cache/ntfy
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s

volumes:
  ntfy_cache:
    driver: local

networks:
  proxy-ntfy:
    external: true

