name: phpmyadmin
services:
  phpmyadmin:
    container_name: phpmyadmin
    env_file:
      - common.env
      - secrets/phpmyadmin.secrets
    environment:
      - PMA_HOST=mariadb
    hostname: ${DOCKER_HOSTNAME}-phpmyadmin
    image: phpmyadmin:apache
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - db-pma
    ports:
      - 127.0.0.1:9671:80

networks:
  db-pma:
    external: true

