name: wallabag
services:
  wallabag:
    container_name: wallabag
    env_file:
      - common.env
      - secrets/wallabag.secrets
    hostname: ${DOCKER_HOSTNAME}-wallabag
    image: wallabag/wallabag
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy-wallabag
      - db-wallabag

networks:
  db-wallabag:
    external: true

  proxy-wallabag:
    external: true
