- name: test server setup
  hosts: all
  become: yes

  tasks:
    - name: Add Docker's official GPG key and Set up Docker repository
      shell: "{{ item }}"
      loop:
        - install -m 0755 -d /etc/apt/keyrings
        - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        - chmod a+r /etc/apt/keyrings/docker.gpg
        - echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable' > /etc/apt/sources.list.d/docker.list

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker Engine, CLI, containerd and plugins
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add user to docker group
      user:
        name: zayon
        groups: docker
        append: yes

    - name: Copy docker daemon.json
      copy:
        src: ../files/etc/docker/daemon.json
        dest: /etc/docker/daemon.json

    - name: Restart docker
      service:
        name: docker
        state: restarted

