location:
    source_directories:
        - /home/zayon/containers_data
    repositories:
        - ssh://pi@localhost:65522/mnt/backup/tidus-backup

retention:
    keep_daily: 7

storage:
    encryption_passphrase: ${BORG_PASSPHRASE}

hooks:
    before_backup:
        - echo "Starting backup"
    after_backup:
        - echo "Backup complete"
    on_error:
        - echo "Backup failed"

