source_directories:
    - /home/zayon/cloud-server-config/docker-configs/secrets
    - /home/zayon/containers_data/nextcloud/data/
    - /home/zayon/containers_data/nextcloud/config/www/nextcloud/config/
    - /home/zayon/containers_data/onlyoffice/
    - /home/zayon/containers_data/mariadb/
    - /home/zayon/containers_data/memos/
    - /home/zayon/containers_data/ntfy/
    - /home/zayon/containers_data/swag/nginx
    - /home/zayon/containers_data/syncthing/
    - /home/zayon/containers_data/vaultwarden/
    - /home/zayon/containers_data/vikunja/
    - /home/zayon/minecraft-server/

repositories:
    - path: ssh://pi@localhost:65522/mnt/backup/tidus-backups
      label: pi

keep_daily: 7

encryption_passphrase: ${BORG_PASSPHRASE}

before_backup:
    - echo "Starting backup"
    - curl -u :${NTFY_TOKEN} -d "Starting Backup ..." https://ntfy.zayon.eu/backups
after_backup:
    - echo "Backup complete"
    - curl -u :${NTFY_TOKEN} -d "Backup finished" https://ntfy.zayon.eu/backups
on_error:
    - echo "Backup failed"
    - curl -u :${NTFY_TOKEN} -d "🚨 Backup failed 🚨" https://ntfy.zayon.eu/backups

